import Head from "next/head";
import Box from "@material-ui/core/Box";
import styles from "../../styles/graphql.module.css";
import { makeStyles } from "@material-ui/core/styles";
import PhoneIcon from "@material-ui/icons/Phone";

import { gql } from "@apollo/client";
import client from "../../constants/apollo-client";

const useStyles = makeStyles((theme) => ({
  felipe: {
    marginTop: 5,
  },
}));

export default function GqlServerSide({ countries }) {
  console.log(countries);
  const classes = useStyles();
  return (
    <div>
      <Head>
        <title>GraphQL Examples </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h3 className={styles.title}>Getting GraphQL</h3>
      <div className={styles.grid}>
        {countries.map((country) => (
          <div key={country?.code?.toString()} className={styles.card}>
            <Box>
              <p>
                {country.emoji} - {country.code}
              </p>
            </Box>
            <Box>
              <h3 className={classes.felipe}>{country.name}</h3>
            </Box>
            <Box>
              <PhoneIcon />
              <span>{country.phone}</span>
            </Box>
          </div>
        ))}
      </div>
    </div>
  );
}

export async function getServerSideProps() {
  const {
    data: { countries },
  } = await client.query({
    query: gql`
      query Countries {
        countries {
          name
          code
          capital
          emoji
          phone
          currency
          continent {
            name
          }
          states {
            name
          }
          languages {
            name
            code
          }
        }
      }
    `,
  });

  return {
    props: {
      countries: countries,
    },
  };
}
